<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile_address', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => '100',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'address_alt' => 
             array(
              'type' => 'string',
              'length' => '100',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => '50',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => '2',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'postal_code' => 
             array(
              'type' => 'string',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
              'unsigned' => '1',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
              'unsigned' => '1',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('profile_address_version', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => '100',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'address_alt' => 
             array(
              'type' => 'string',
              'length' => '100',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => '50',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => '2',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'postal_code' => 
             array(
              'type' => 'string',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '10',
              'notnull' => '',
              'unsigned' => '1',
             ),
             'version' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
              'notnull' => '',
              'unsigned' => '1',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             ));
        $this->createForeignKey('profile_address', 'profile_address_profile_id_profile_id', array(
             'name' => 'profile_address_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->createForeignKey('profile_address_version', 'profile_address_version_id_profile_address_id', array(
             'name' => 'profile_address_version_id_profile_address_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'profile_address',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('profile_address', 'profile_address_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('profile_address_version', 'profile_address_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('profile_address');
        $this->dropTable('profile_address_version');
        $this->dropForeignKey('profile_address', 'profile_address_profile_id_profile_id');
        $this->dropForeignKey('profile_address_version', 'profile_address_version_id_profile_address_id');
        $this->removeIndex('profile_address', 'profile_address_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('profile_address_version', 'profile_address_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}